"""Typed models for the agentic advisory system."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any


@dataclass(frozen=True)
class EvidenceItem:
    """One traceable fact supporting an advisory recommendation."""

    field_name: str
    value: Any
    source_table: str

    def to_dict(self) -> dict[str, Any]:
        """Return a serialisable evidence item."""

        return asdict(self)


@dataclass(frozen=True)
class AgentRecommendation:
    """Recommendation generated by one specialist advisory agent."""

    recommendation_id: str
    agent_name: str
    target_role: str
    recommendation_type: str
    priority: str
    part_number: str | None
    title: str
    recommendation: str
    rationale: str
    forecast_confidence: str | None
    evidence: list[EvidenceItem]
    human_approval_required: bool
    automatic_action_allowed: bool
    status: str

    def to_dict(self) -> dict[str, Any]:
        """Return a serialisable recommendation."""

        result = asdict(self)

        result["evidence"] = [
            item.to_dict()
            for item in self.evidence
        ]

        return result


@dataclass(frozen=True)
class AssuranceFinding:
    """Finding produced by the final assurance agent."""

    recommendation_id: str
    assurance_status: str
    finding_type: str
    finding_message: str
    evidence_complete: bool
    governance_compliant: bool
    approved_for_management_display: bool

    def to_dict(self) -> dict[str, Any]:
        """Return a serialisable assurance finding."""

        return asdict(self)